mechmotum/cyipopt

.gitignore
README.rst
src/cyipopt.pyx
vagrant/Vagrantfile

The commit list presented are related with this two main changes:
1 - Added initialization support for mult_g, mult_x_L and mult_x_U. The Matlab interface support that you can provide values to initialize these structures, so to keep compatibility with a port that I made from Matlab to python, I need to add this because it changes how the problem is solved in ipopt, also the number of iterations in the optimization process.
Example of my initialization::
x0 = npmean( nparray([ lowerbounds,  upperbounds]),axis=0 )
zl = npmax(npabs(x0),10)
zu = npcopy(zl)
lagrange = npones(obj.m)
xot, info = nlp.solve(x=x0,lagrange=lagrange,zl=zl,zu=zu)
The defintion for the solve method is now::
def solve(self,x,lagrange=[],zl=[],zu=[]):
And the changes in the structure creation are::
#cdef …

Initialization support and vagrant env

---

ipopt/ipopt_wrapper.py

This PR fixes a bug in the options arguments for Python3. More specifically, ipopt expects a byte string, but all strings in Python3 are unicode strings by default. Hence, the keys in the options dictionary need to be converted accordingly.

fixed python3 bug in options

---

README.rst
doc/source/install.rst

The cyipopt recipe has been merged at conda forge: https://github.com/conda-forge/staged-recipes/pull/2273. The binaries should be available some time today.

Added conda installation instructions and cleaned up the README some.

---

.travis.yml
src/cyipopt.pyx
test/examplehs071.py
test/exception_handling.py
test/lasso.py
test/rosen.py

- Also added the simple minimize_ipopt example to the tests.

Python 2 and 3 now accept strings and bytes for addOption, fixes #27.

---

README.rst
appveyor.yml
setup.py

Add an appveyor Windows CI build.

---

README.rst

Added stuff learned from #52
This should close #52

Add some more details on Windows installation

---

CHANGELOG
setup.py

Tested locally:
```
moorepants@agni:~/src/cyipopt$ python setup.py 
Package ipopt was not found in the pkg-config search path.
Perhaps you should add the directory containing `ipopt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ipopt' found
Traceback (most recent call last):
File "setup.py", line 101, in <module>
**pkgconfig('ipopt'))]
File "setup.py", line 57, in pkgconfig
raise OSError(msg.format(list(packages)))
OSError: pkg-config was not able to find any of the requested packages (['ipopt']) on your system. Make sure pkg-config can discover the .pc files associated with the installed packages.
```

Added OSError to handle pkg-config not finding ipopt.

---

CHANGELOG
README.rst
appveyor.yml
setup.py

Issue #62 
This updates the `setup.py` files to work with precompiled Ipopt 3.13.XX binaries for Windows (tested with Ipopt 3.13.2 from their [Github](https://github.com/coin-or/Ipopt/releases)). As explained in the Issue thread, this breaks compatibility with older Ipopt precompiled versions because of the different structure. According to feedback, a environment variable could be introduced to specify the Ipopt version.
Edit: I don't know if this has to do with the new Ipopt build system, but this works equally on anaconda and python.org Python with the dependencies installed via pip.

Add Ipopt 3.13 support for Windows

---

setup.py

It was decided upstream to be consistent with the official IPOPT windows
binaries. See:
- https://github.com/conda-forge/ipopt-feedstock/issues/53
- https://github.com/conda-forge/ipopt-feedstock/pull/58

Changes conda-forge windows lib name to ipopt-3

---

cyipopt/cython/ipopt_wrapper.pyx

Currently `cyipopt` logs messages to the Python root logging namespace.  This makes it challenging when building larger applications that embed `cyipopt`, as you cannot for example easily enable `INFO` logging for the application without also also getting `INFO` log messages from `cyipopt`.
This PR moves `cyipopt` logging into the `'cyipopt'` logging namespace to allow users more fine-grained control of the logged messages.

Log cyipopt messages to the 'cyipopt' logging namespace

---

CHANGELOG.rst
cyipopt/cython/ipopt_wrapper.pyx
cyipopt/tests/unit/test_deprecations.py

This PR adds a new function `set_logging_level` following the new PEP8-style API to replace the old `setLoggingLevel`. Calling `setLoggingLevel` now also issues a `FutureWarning` following the pattern for other functions/classes/methods that are to be deprecated. The issuing of this `FutureWarning` is also check for by a test in `cyipopt/tests/unit/test_deprecations.py`.
This PR also includes some tidying up of `cyipopt/cython/ipopt_wrapper.pyx` (mostly code reformatting to make it easier to read, removing unnecessary uncommented code etc.).

Add PEP8 API for old `setLoggingLevel` function

---

.travis.yml
CHANGELOG.rst
conda/cyipopt-dev.yml
cyipopt/__init__.py
cyipopt/cython/ipopt_wrapper.pyx
cyipopt/scipy_interface.py
cyipopt/tests/conftest.py
docs/rtd-env.yml
docs/source/install.rst
examples/hs071.py
examples/lasso.py
requirements.txt
setup.py

Remove six and future

---

docs/source/tutorial.rst
examples/hs071_scipy_jax.py

As we all know, calculating derivatives by hand can be quite error-prone. During the last months, I often used the [JAX](https://jax.readthedocs.io/en/latest/index.html) library to evaluate gradients and (dense) jacobians via AD (algorithmic differentiation), so I thought it might be an interesting example.

Added example using JAX and the scipy interface.

---

.github/workflows/run-tests.yml

Adds configuration to use github actions for testing.

---

cyipopt/cython/ipopt_wrapper.pyx
cyipopt/ipopt_wrapper.py
cyipopt/scipy_interface.py
cyipopt/tests/unit/test_scipy_optional.py
docs/source/tutorial.rst
examples/hs071_scipy_jax.py

Implements #99 and #122.
- Adds support for objective hessian and constraint Hessians through an additional `hess` field in the constraint dictionary.  The hessian must have the signature `hess(x,v) -> np.ndarray` and return `v[0] * Hg1_(x) + ... + v[m-1] * Hg_m(x)`. Here, `v` is the np.ndarray with shape `m` containing the lagrangian multipliers for the constraint and `Hg_i` denotes the hessian matrix of the constraint component `g_i : R^N -> R`.
Current limitations:
- No support for NonlinearConstraint objects.
- No support for objective hessian matrix-vector product `hessp`.
- In case one passes the hessian for at least one constraint or the objective, we need the Hessians for all constraints and the objective.

Add support for objective and constraint hessians and `jac=True` option for constraints in the scipy interface

---

cyipopt/cython/ipopt_wrapper.pyx

Follow-up PR as discussed in [this thread](https://github.com/mechmotum/cyipopt/pull/132). It's basically just a one-line change to avoid KeyErrors in case IPOPT returns a status that `cyipopt` cannot (yet) deal with.
Side-note: I considered adding a test for this, somewhat along the lines of
```python
import ipopt_wrapper
def test_unknown_ipopt_status(
monkeypatch, hs071_initial_guess_fixture, hs071_problem_instance_fixture
):
"""Check if cyipopt is able to gracefully handle unknown IPOPT
statuses.
"""
unknown_status = -42
assert unknown_status not in ipopt_wrapper.STATUS_MESSAGES
def mock_solve(*args, **kwargs):
return unknown_status
monkeypatch.setattr(ipopt_wrapper, "IpoptSolve", mock_solve)
x0 = hs071_initial_guess_fixture
nlp = hs071_problem_instance_fixture
_, info = nlp.solve(x0) …
```

Avoid KeyError upon unknown IPOPT return statuses.

---

cyipopt/scipy_interface.py
cyipopt/version.py
examples/exception_handling.py
examples/hs071.py
examples/hs071_scipy_jax.py
examples/lasso.py
setup.py

Adds a shebang to `examples/rosen.py`, to match the other examples.
Sets execute permission on all files with shebangs—the examples, plus `setup.py`—without which the shebangs have little value.

A little consistency in shebangs and execute bits

---

.github/workflows/docs.yml
.github/workflows/test.yml
.github/workflows/tests.yml

This PR is intended to diagnose and fix currently failing CI workflows occurring only with macOS and Python 3.9 (encountered first in PR #146). I hypothesise that this is due to use of [python setup.py install](https://github.com/mechmotum/cyipopt/blob/89401cf28345dd59137b272b95f13f0a6d481886/.github/workflows/test.yml#L31) for package installation becoming [deprecated](https://docs.python.org/3/install/) with the deprecation of distutils in preference of setuptools.
Currently all CI workflows raise related warnings following the call of `python setup.py install`. A copy of a revenant message from a random recent CI run is copied below:
```
[1] Run python setup.py install
[2]   python setup.py install
[3]   shell: /bin/bash -l {0}
[4]   env:
[5]    CONDA_PKGS_DIR: …
```

Remove deprecated setup.py install approach

---

docs/source/tutorial.rst
examples/hs071_scipy_jax.py

Improve the jax example

---

cyipopt/scipy_interface.py

```
=========================================== warnings summary ============================================
cyipopt/scipy_interface.py:29
/home/moorepants/src/cyipopt/cyipopt/scipy_interface.py:29: DeprecationWarning: Please use `MemoizeJac` from the `scipy.optimize` namespace, the `scipy.optimize.optimize` namespace is deprecated.
from scipy.optimize.optimize import MemoizeJac
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

Avoid SciPy deprecation warning.

---

docs/source/install.rst
pyproject.toml

Adds [`pyproject.toml` file to specify the build dependencies for this package](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/). This removes the need to have e.g. `setuptools` before running `pip install cyipopt`.
Docs are updated accordingly.
On a related note, I think it's worth considering removing `requirements.txt` to reduce confusion.

Reduce manual  pre-installation requirements via pyproject.toml

---

cyipopt/scipy_interface.py
cyipopt/tests/unit/test_scipy_optional.py
docs/source/tutorial.rst

Closes #98.
This PR adds support for sparse jacobians in the scipy interface.
- The user can pass dense and sparse constraint jacobians and even mix both
- Each provided jacobian is expected to be a function that returns either a `np.ndarray`(dense) or a `scipy.sparse.coo_array` (sparse).
- Under the hood, all jacobians are converted to sparse matrices in the COO format, i.e. [`coo_array`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_array.html#scipy.sparse.coo_array).
PS: After this PR, the three functions `get_constraint_bounds`, `get_constraint_dimensions`, and `get_sparse_jacobian_structure` will be called in order to create the Ipopt NLP problem before the problem is passed to Ipopt. Since each of these functions will evaluate the constraints and jacobians, I …

Add support for sparse jacobians in the scipy-interface

---

.github/workflows/docs.yml
.github/workflows/test.yml
.github/workflows/tests.yml
cyipopt/tests/unit/test_scipy_optional.py

This PR attempts to fix #177 by replacing `conda-build-version` in `conda-incubator/setup-miniconda` step of all jobs in all GitHub Actions workflows with `mamba-version`, as per https://github.com/conda-incubator/setup-miniconda/issues/116.

Change conda-build-version to mamba-version

---

cyipopt/scipy_interface.py

Import MemoizeJac from scipy.optimize._optimize.

---

examples/lasso.py

In examples/lasso.py, change np.float (which was deprecated in numpy 1.20 and removed in numpy 1.24) to np.float64.

Don’t use deprecated/removed np.float alias

---

cyipopt/scipy_interface.py
docs/source/conf.py

Thanks for maintaining cyipopt! 
I'm a SciPy maintainer, and we've discussed the possibility of adding `method='ipopt'` to `scipy.optimize.minimize` (with cyipopt as an optional dependency due to the license incompatibility). For now, though, we thought we'd try to help improve the compatibility between `cyipopt.minimize_ipopt` and `scipy.optimize.minimize` interfaces.
To start, this PR begins to add formal documentation to `cyipopt.minimize_ipopt`.
Please let me know if you're interested in continued contributions. In this PR, for example, I could also try to add:
- More complete documentation of `constraints`
- References (e.g. Ipopt documentation)
- Examples
As follow-up work, ideas include:
- Support for the `method` parameter (i.e. allowing use of all `scipy.optimize.minimize` …

DOC: minimize_ipopt: add documentation

---

cyipopt/scipy_interface.py
cyipopt/tests/unit/test_scipy_optional.py

args & kwargs work with all user funcs in minimize_ipopt
- Passed in args and kwargs to all IpoptProblemWrapper.
- Added a unit test with args and kwargs for all funcs.

args and kwargs now work fully for minimize_ipopt

---

cyipopt/scipy_interface.py
cyipopt/tests/unit/test_scipy_optional.py

Although `IpoptProblemWrapper` contains some input validation, `minimize_ipopt` was missing input validation of other parameters. For instance, `callback` was ignored silently, and invalid values of arguments could lead to confusing errors deeper in the code. This PR systematically adds basic input validation and tests to `minimize_ipopt`.

MAINT: minimize_cyipopt: add input validation

---

cyipopt/scipy_interface.py
cyipopt/tests/unit/test_scipy_optional.py

As reported in https://github.com/mechmotum/cyipopt/pull/194#discussion_r1155423756, `minimize_ipopt` fails on the [`scipy.optimize.minimize`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html) example with three constraints. This is due to a [late binding gotcha](https://docs.python-guide.org/writing/gotchas/#late-binding-closures) when the constraint Jacobians are defined in a loop. This fixes that bug and demonstrates that the example problem is solved successfully after the fix.
<details>
Try me before and after.
```python3
from cyipopt import minimize_ipopt
fun = lambda x: (x[0] - 1)**2 + (x[1] - 2.5)**2
cons = ({'type': 'ineq', 'fun': lambda x:  x[0] - 2 * x[1] + 2},
{'type': 'ineq', 'fun': lambda x: -x[0] - 2 * x[1] + 6},
{'type': 'ineq', 'fun': …
```

MAINT: minimize_ipopt: fix late binding bug when defining constraint Jacobians

---

requirements.txt
setup.py

Works around, but does not fix, https://github.com/mechmotum/cyipopt/issues/211.
In addition to upper-bounding the version of Cython, this also drops Cython from `install_requires`, since it doesn’t appear to be a real runtime dependency.

Pin Cython<3 until compatibility can be fixed

---

cyipopt/__init__.py
cyipopt/cython/ipopt_wrapper.pyx
cyipopt/exceptions.py
cyipopt/tests/integration/test_hs071.py
docs/source/reference.rst

- New `cyipopt.exceptions` module that contains only `CyIpoptEvaluationError` for now
- In function and derivative callbacks, if `CyIpoptEvaluationError` is raised by user's callback, we ignore the exception and return `false` to Ipopt
- Test this behavior on HS071. Ipopt completes the solve (by cutting the step size) if the error occurs in the objective or constraints, but quits immediately if the error occurs in the derivatives.
The tests are integration tests, which I've included in `test_hs071.py`. I can move these to their own module if that would be more appropriate.

Add `CyIpoptEvaluationError` and handle in callbacks

---

.github/workflows/docs.yml
.github/workflows/tests.yml
.github/workflows/windows.yml
setup.py

At some point we disabled the appveyor windows CI run that would download an official Ipopt windows release and test building against that. In our documentation it implies that you can take the contents of that Ipopt zip file and place them adjacent to the setup.py file and they'd get picked up. 
https://cyipopt.readthedocs.io/en/stable/install.html#from-source-on-windows says: "After Ipopt is extracted, the bin, lib and include folders should be in the root cyipopt directory, i.e. adjacent to the setup.py file." but it seems like we removed the support for this and it isn't present here:
https://github.com/mechmotum/cyipopt/blob/master/setup.py#L187
This adds back the functionality as well as a Github action to test that it works.

Now picks up Windows Ipopt binary files that are adjacent to setup.py (restores regression)

---

cyipopt/cython/ipopt_wrapper.pyx
cyipopt/tests/unit/test_deriv_errors.py

If the indices are not correct, then ipopt seems to segfault, so the errors should be caught earlier in the interface.

Add sanity checks to Jacobian / Hessian indices

---

cyipopt/tests/unit/test_scipy_ipopt_from_scipy.py

During development of gh-207, I commented out `test_gh1758` because Ipopt found the problem to be infeasible. At some point (maybe gh-208), this seems to have been fixed. This PR uncomments the test, which now passes.

TST: minimize_ipopt: add back test_gh1758

---

cyipopt/cython/ipopt_wrapper.pyx
pyproject.toml
setup.py

This is an attempt to fix #211:
- All callbacks are now marked `noexpect` with exceptions being handled (stored) internally
- A large `try` / `expect` block is used in the callbacks, where code outside of the blocks should not throw (only stack allocations)
- The large Jacobian / Hessian callbacks have been split up into value / structure callbacks
- Cython restriction to <3 was removed

Enable support for cython 3

---

cyipopt/scipy_interface.py
cyipopt/tests/unit/test_scipy_ipopt_from_scipy.py
cyipopt/tests/unit/test_scipy_optional.py

closes gh-115, which requested that `eps`, the finite difference step size, be exposed as an option.

ENH: expose 'eps' option for finite difference step size

---

cyipopt/scipy_interface.py
cyipopt/tests/unit/test_scipy_optional.py

Covert tol to float before passing to ipopt.

---

MANIFEST.in

https://github.com/mechmotum/cyipopt/issues/237#issuecomment-1826793291
This PR seems to be effective for `python3 setup.py sdist` but not for `python3 -m build`.

Add examples/ and docs/requirements.txt to source distribution

---

cyipopt/cython/ipopt_wrapper.pyx

`"constrains"` -> `"constraints"`

Error message spelling indicates incorrect callback name

---

docs/source/tutorial.rst

This is an edit to the tutorial documentation.
Original tutorial is not entirely clear on what the jacobian/hessian jacobian/hessianstructure methods should return when providing them as sparse matrices.
I'm not sure if this is the best way to add this information. The structure of the method returns is shown in the example below it, but, as a user, it took me some time to see how best to structure the returns (I also mistakenly tried to use a scipy sparse matrix structure as a return at one point).

Add clarity to jacobian/hessianstructure methods

---

.github/workflows/tests.yml
docs/source/install.rst

This adds simple instructions on how to add HSL binaries to windows conda install of cyipopt.  - tested only on my machine, so hopefully it works for others.

Add install instructions for HSL on windows 

---

.github/workflows/tests.yml

I had things set up to build against netlib blas/lapack and then to install conda's os preferred blas/lapack implementation to run the tests, but it seems that the netlib version was hanging around and things weren't working with the macosx builds failing with current conda forge packages. I don't actually need to do this netlib/no netlib test, as it is done downstream in the cyipopt-feedstock for conda forge.

Removed the netlib build and simply build with the os preferred lapack.

---

cyipopt/cython/ipopt_wrapper.pyx
cyipopt/tests/conftest.py
cyipopt/tests/integration/test_hs071.py

This should explain / fix #266

Add documentation / tests for warm starting

---

cyipopt/cython/ipopt_wrapper.pyx
cyipopt/scipy_interface.py
docs/source/conf.py

This should fix #153 and hopefully generally improve readability of the documentation of the callbacks.

Improve documentation of callback functions

---

setup.py

Hello,
thank you for this project.
This change is rather small: it does not assume to know the folder contents of the ipopt `bin` folder, but reads them out. When using this with the latest release from the ipopt github repo, this is what is printed out:
```sh
Found ipopt binaries ['coinmumps-3.dll', 'ipopt-3.dll', 'ipoptamplinterface-3.dll', 'libifcoremd.dll', 'libiomp5md.dll', 'libmmd.dll', 'sipopt-3.dll', 'svml_dispmd.dll'].
```
Let me know if this is helpful.
Best,
Phil

read in files from ipopt bin folder
